[workspace]
members = [
    "crates/plcc-st",
    "crates/plcc-hir",
    "crates/plcc-codegen",
    "crates/plcc-runtime",
    "crates/plcc-cli",
    "crates/plcc-hal", "crates/plcc-stdlib", "crates/plcc-plcopen", "crates/plcc-twincat", "crates/plcc-l5x",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"
