[package]
name = "plcc-wasm-link"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror = "2.0.21"
wasm-encoder = { version = "0.260.0", default-features = false, features = ["std"] }
wasmparser = { version = "0.260.0", default-features = false, features = ["std"] }

[dev-dependencies]
wasmi = { version = "2.0.0", default-features = false, features = ["stable", "std", "validate"] }
wasmparser = { version = "0.260.0", features = ["validate", "features", "simd"] }
