[package]
name = "plcc-codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
inkwell = { version = "0.8.0", features = ["llvm21-1", "llvm21-1-force-static"] }
miette = { version = "7.6.0", features = ["fancy"] }
thiserror = "2.0.18"
plcc-hir = { version = "0.1.0", path = "../plcc-hir" }
plcc-st = { version = "0.1.0", path = "../plcc-st" }

[dev-dependencies]
regex = "1.12.3"
plcc-st = { path = "../plcc-st" }
plcc-runtime = { path = "../plcc-runtime" }
plcc-stdlib = { path = "../plcc-stdlib" }
