// SPDX-License-Identifier: MPL-2.0

//! `--emit-header` and `--emit-symbols`: the runtime contract as a C header and as
//! JSON. Both are rendered from [`RuntimeContract`], which carries the layouts LLVM
//! computed for the target, so every struct in the header is checked against them
//! with `_Static_assert`.

use crate::compiler::contract::{CType, FieldInfo, StructInfo};
use crate::RuntimeContract;
use serde_json::{Value, json};
use std::fmt::Write as _;

/// C and C++ keywords that are legal IEC identifiers. A field with one of these
/// names gets a trailing underscore in the header.
const C_KEYWORDS: &[&str] = &[
    "auto", "break", "case", "char", "const", "continue", "default", "do", "double", "else",
    "enum", "extern", "float", "for", "goto", "if", "inline", "int", "long", "register",
    "restrict", "return", "short", "signed", "sizeof", "static", "struct", "switch", "typedef",
    "union", "unsigned", "void", "volatile", "while", "bool", "class", "delete", "new",
    "operator", "private", "protected", "public", "template", "this", "throw", "try",
    "virtual", "namespace", "using", "friend", "mutable", "explicit", "true", "false",
    "catch", "typename", "asm", "export",
];

/// The C spelling of an IEC identifier used as a struct member.
pub fn c_member(name: &str) -> String {
    if C_KEYWORDS.contains(&name) {
        format!("{name}_")
    } else {
        name.to_string()
    }
}

/// `s` escaped for a C string literal.
fn c_string(s: &str) -> String {
    s.chars()
        .flat_map(|c| match c {
            '"' | '\\' => vec!['\\', c],
            c if c.is_ascii_graphic() || c == ' ' => vec![c],
            _ => vec!['?'],
        })
        .collect()
}

fn macro_ident(s: &str) -> String {
    s.chars()
        .map(|c| if c.is_ascii_alphanumeric() { c.to_ascii_uppercase() } else { '_' })
        .collect()
}

fn declarator(ty: &CType, name: &str) -> String {
    let mut dims = String::new();
    let mut cur = ty;
    while let CType::Array(elem, n) = cur {
        let _ = write!(dims, "[{n}]");
        cur = elem;
    }
    match cur {
        CType::Scalar(s) if s.ends_with('*') => format!("{s}{name}{dims}"),
        CType::Scalar(s) | CType::Named(s) => format!("{s} {name}{dims}"),
        CType::Opaque { size, align } => {
            format!("PLCC_ALIGNAS({align}) uint8_t {name}{dims}[{size}]")
        }
        CType::Array(..) => unreachable!("arrays are unwrapped above"),
    }
}

fn emit_struct(out: &mut String, s: &StructInfo, tag: &str) {
    let tag_name = s.c_name.trim_end_matches("_t");
    let _ = writeln!(out, "/* {tag} {} */", s.iec_name);
    let _ = writeln!(out, "typedef struct {tag_name} {{");
    if s.fields.is_empty() {
        // An empty struct is not valid C; the state is never read.
        let _ = writeln!(out, "    uint8_t plcc_empty_;");
    }
    for f in &s.fields {
        let mut note = format!("{} @ {}", f.iec_type, f.offset);
        if let Some(at) = &f.at {
            let _ = write!(note, ", AT {at}: lives in the process image, slot unused");
        }
        if f.retain {
            note.push_str(", RETAIN");
        }
        let _ = writeln!(out, "    {}; /* {note} */", declarator(&f.c_type, &c_member(&f.name)));
    }
    let _ = writeln!(out, "}} {};", s.c_name);
    if !s.fields.is_empty() {
        let _ = writeln!(
            out,
            "PLCC_STATIC_ASSERT(sizeof({}) == {}, \"{} size differs from the compiled layout\");",
            s.c_name, s.size, s.c_name
        );
        for f in &s.fields {
            assert_offset(out, &s.c_name, f);
        }
    }
    out.push('\n');
}

fn assert_offset(out: &mut String, c_name: &str, f: &FieldInfo) {
    let _ = writeln!(
        out,
        "PLCC_STATIC_ASSERT(offsetof({c_name}, {m}) == {o}, \"{c_name}.{m} offset differs from the compiled layout\");",
        m = c_member(&f.name),
        o = f.offset
    );
}

/// Render the C header for `contract`.
pub fn c_header(contract: &RuntimeContract, guard: &str) -> String {
    let c = contract;
    let mut o = String::new();
    let g = macro_ident(guard);
    let _ = writeln!(
        o,
        "/* Generated by plcc for {} — do not edit.\n * Runtime contract: docs/process-image.md (ABI version {}). */",
        c.triple, c.abi_version
    );
    let _ = writeln!(o, "#ifndef {g}\n#define {g}\n");
    o.push_str("#include <stddef.h>\n#include <stdint.h>\n\n");
    o.push_str("#ifdef __cplusplus\nextern \"C\" {\n#define PLCC_STATIC_ASSERT(c, m) static_assert(c, m)\n#define PLCC_ALIGNAS(n) alignas(n)\n#else\n#define PLCC_STATIC_ASSERT(c, m) _Static_assert(c, m)\n#define PLCC_ALIGNAS(n) _Alignas(n)\n#endif\n\n");
    let _ = writeln!(o, "#define PLCC_ABI_VERSION {}u", c.abi_version);
    let _ = writeln!(o, "#define PLCC_TARGET_TRIPLE \"{}\"", c.triple);
    let _ = writeln!(o, "#define PLCC_TARGET_CPU \"{}\"", c_string(&c.cpu));
    let _ = writeln!(o, "#define PLCC_TARGET_FEATURES \"{}\"", c_string(&c.features));
    if let Some(d) = &c.device {
        let _ = writeln!(o, "#define PLCC_DEVICE_ID \"{}\"", c_string(&d.id));
        let _ = writeln!(o, "#define PLCC_DEVICE_MANIFEST_VERSION {}u", d.version);
    }
    let _ = writeln!(o, "#define PLCC_POINTER_SIZE {}", c.pointer_size);
    let _ = writeln!(o, "#define PLCC_BIG_ENDIAN {}", c.big_endian as u8);
    let _ = writeln!(
        o,
        "PLCC_STATIC_ASSERT(sizeof(void *) == PLCC_POINTER_SIZE, \"header generated for a different target ({})\");\n",
        c.triple
    );

    // ── Process image ──
    o.push_str("/* ── Process image ─────────────────────────────────────────────────\n * %I inputs, %Q outputs, %M memory. Native byte order. CODESYS addressing:\n * %IXb.x = bit x of byte b, %IBn = byte n, %IWn = bytes 2n..2n+1,\n * %IDn = bytes 4n..4n+3, %ILn = bytes 8n..8n+7. */\n");
    for (i, (letter, sym)) in [('I', "plcc_image_i"), ('Q', "plcc_image_q"), ('M', "plcc_image_m")]
        .iter()
        .enumerate()
    {
        let _ = writeln!(o, "#define PLCC_IMAGE_{letter}_SIZE {}u", c.image_sizes[i]);
        let _ = writeln!(o, "extern uint8_t {sym}[];");
    }
    o.push_str(
        "\ntypedef struct plcc_process_image {\n    uint8_t *input;\n    uint32_t input_size;\n    uint8_t *output;\n    uint32_t output_size;\n    uint8_t *memory;\n    uint32_t memory_size;\n} plcc_process_image_t;\n\n",
    );

    // ── Tasks ──
    o.push_str("/* ── Tasks ───────────────────────────────────────────────────────── */\n");
    o.push_str("typedef struct plcc_program_instance {\n    const char *name;          /* \"RESOURCE.instance\", or the PROGRAM name */\n    const char *program_type;  /* PROGRAM POU name */\n    void (*init)(void *state);\n    void (*scan)(void *state);\n    void *state;               /* statically allocated instance state */\n    uint64_t state_size;\n} plcc_program_instance_t;\n\n");
    o.push_str("typedef struct plcc_task {\n    const char *name;\n    int64_t interval_ns;       /* 0: not cyclic (event or free-running) */\n    uint32_t priority;         /* IEC: 0 is the highest priority */\n    uint32_t program_count;\n    uint8_t (*single)(void);   /* current SINGLE value, or NULL */\n    const plcc_program_instance_t *programs;\n} plcc_task_t;\n\n");
    o.push_str("typedef struct plcc_retain_region {\n    const char *name;\n    void *data;\n    uint64_t size;\n} plcc_retain_region_t;\n\n");
    o.push_str("typedef struct plcc_app {\n    uint32_t abi_version;\n    uint32_t task_count;\n    const plcc_task_t *tasks;\n    const plcc_process_image_t *image;\n    void (*init)(void);\n    void (*run_task)(uint32_t task);\n    const plcc_retain_region_t *retain;\n    uint32_t retain_count;\n    uint32_t retain_signature;\n} plcc_app_t;\n\n");
    o.push_str("extern const plcc_app_t plcc_app;\nextern const plcc_task_t plcc_tasks[];\nextern const plcc_process_image_t plcc_process_image;\nextern const plcc_retain_region_t plcc_retain_regions[];\nconst plcc_app_t *plcc_get_app(void);\n/* Initialize every variable of every program instance. Call once at start. */\nvoid plcc_init(void);\n/* Run every program instance of task `task` once, in declaration order. */\nvoid plcc_run_task(uint32_t task);\n\n");
    let _ = writeln!(o, "#define PLCC_TASK_COUNT {}u", c.tasks.len());
    for (i, t) in c.tasks.iter().enumerate() {
        let m = macro_ident(&t.name);
        let _ = writeln!(
            o,
            "#define PLCC_TASK_{m} {i}u\n#define PLCC_TASK_{m}_INTERVAL_NS {}ll\n#define PLCC_TASK_{m}_PRIORITY {}u",
            t.interval_ns, t.priority
        );
    }
    let retain_size: u64 = c.retain.iter().map(|r| r.size).sum();
    let _ = writeln!(
        o,
        "\n#define PLCC_RETAIN_COUNT {}u\n#define PLCC_RETAIN_SIZE {}u\n#define PLCC_RETAIN_SIGNATURE 0x{:08x}u\n",
        c.retain.len(),
        retain_size,
        c.retain_signature
    );

    // ── AT bindings ──
    o.push_str("/* ── AT bindings ─────────────────────────────────────────────────── */\n");
    o.push_str("typedef struct plcc_at_binding {\n    const char *name;       /* \"Scope.variable\" */\n    char area;              /* 'I', 'Q' or 'M' */\n    char size;              /* 'X', 'B', 'W', 'D' or 'L' */\n    int8_t bit;             /* 0..7 for X, -1 otherwise */\n    uint32_t byte_offset;\n    uint32_t byte_size;\n    const char *iec_type;\n} plcc_at_binding_t;\n\n");
    let _ = writeln!(o, "#define PLCC_AT_COUNT {}u", c.at_bindings.len());
    for b in &c.at_bindings {
        let m = format!("PLCC_AT_{}_{}", macro_ident(&b.scope), macro_ident(&b.name));
        let sym = match b.area {
            'I' => "plcc_image_i",
            'Q' => "plcc_image_q",
            _ => "plcc_image_m",
        };
        let _ = writeln!(o, "/* {}.{} AT {} : {} */", b.scope, b.name, b.address, b.iec_type);
        let _ = writeln!(o, "#define {m}_AREA '{}'", b.area);
        let _ = writeln!(o, "#define {m}_OFFSET {}u", b.byte_offset);
        let _ = writeln!(o, "#define {m}_BIT {}", b.bit.map(|x| x as i32).unwrap_or(-1));
        let _ = writeln!(o, "#define {m}_PTR (&{sym}[{}])", b.byte_offset);
    }
    if !c.at_bindings.is_empty() {
        o.push_str("\n#if defined(__GNUC__) || defined(__clang__)\n__attribute__((unused))\n#endif\nstatic const plcc_at_binding_t plcc_at_bindings[] = {\n");
        for b in &c.at_bindings {
            let _ = writeln!(
                o,
                "    {{\"{}.{}\", '{}', '{}', {}, {}u, {}u, \"{}\"}},",
                b.scope,
                b.name,
                b.area,
                b.size_prefix,
                b.bit.map(|x| x as i32).unwrap_or(-1),
                b.byte_offset,
                b.size,
                b.iec_type
            );
        }
        o.push_str("};\n");
    }
    o.push('\n');

    // ── State layouts ──
    o.push_str("/* ── State layouts (verified against the compiled layout) ─────────── */\n");
    let program_types: std::collections::HashSet<usize> =
        c.programs.iter().map(|p| p.type_index).collect();
    for (i, s) in c.types.iter().enumerate() {
        let tag = if program_types.contains(&i) {
            "PROGRAM"
        } else if s.c_name.starts_with("plcc_fb_") {
            "FUNCTION_BLOCK"
        } else {
            "STRUCT"
        };
        emit_struct(&mut o, s, tag);
    }
    for p in &c.programs {
        let t = &c.types[p.type_index].c_name;
        let _ = writeln!(o, "void {}({t} *state);\nvoid {}({t} *state);", p.init_fn, p.scan_fn);
    }
    for inst in &c.instances {
        let t = c
            .programs
            .iter()
            .find(|p| p.name == inst.program)
            .map(|p| c.types[p.type_index].c_name.clone())
            .unwrap_or_else(|| "uint8_t".into());
        let _ = writeln!(o, "extern {t} {}; /* instance {} */", inst.symbol, inst.name);
    }
    if let Some(gs) = &c.globals {
        o.push('\n');
        emit_struct(&mut o, gs, "VAR_GLOBAL");
        o.push_str("extern plcc_globals_t plcc_globals;\n");
    }

    // ── Runtime faults ──
    o.push_str("\n/* ── Runtime faults ────────────────────────────────────────────────\n * Compiled code calls plcc_fault() when an ST operation cannot continue (as\n * CODESYS raises an exception and stops the task). It must not return: if it\n * does, the compiled code executes a trap instruction. The object carries a weak\n * default that traps; define plcc_fault in the runtime to override it — put the\n * outputs in a safe state, stop the tasks, report `code` and `where`\n * (\"file:line:col: POU\", or just the POU). See docs/runtime-symbols.md. */\n");
    for code in plcc_runtime::fault::FaultCode::ALL {
        let note = match code {
            plcc_runtime::fault::FaultCode::DivByZero => "",
            plcc_runtime::fault::FaultCode::ArrayBounds => " /* Logix (L5X) code only */",
            _ => " /* reserved: not raised yet */",
        };
        let _ = writeln!(
            o,
            "#define PLCC_FAULT_{} {}u{note}",
            code.c_name(),
            code.code()
        );
    }
    let _ = writeln!(
        o,
        "#define PLCC_FAULT_USER_BASE 0x{:x}u /* first code free for the runtime's own faults */",
        plcc_runtime::fault::FAULT_USER_BASE
    );
    o.push_str("void plcc_fault(uint32_t code, const char *where);\n");

    let _ = writeln!(o, "\n#ifdef __cplusplus\n}}\n#endif\n#endif /* {g} */");
    o
}

fn struct_json(s: &StructInfo) -> Value {
    json!({
        "c_name": s.c_name,
        "iec_name": s.iec_name,
        "size": s.size,
        "align": s.align,
        "fields": s.fields.iter().map(|f| json!({
            "name": f.name,
            "iec_type": f.iec_type,
            "offset": f.offset,
            "size": f.size,
            "retain": f.retain,
            "at": f.at,
        })).collect::<Vec<_>>(),
    })
}

/// Render the symbol table (`--emit-symbols`) for `contract`.
pub fn symbols_json(contract: &RuntimeContract) -> String {
    let c = contract;
    let v = json!({
        "abi_version": c.abi_version,
        "target": c.triple,
        "cpu": c.cpu,
        "features": c.features,
        "device": c.device.as_ref().map(|d| json!({ "id": d.id, "version": d.version })),
        "pointer_size": c.pointer_size,
        "byte_order": if c.big_endian { "big" } else { "little" },
        "image": {
            "I": { "symbol": "plcc_image_i", "size": c.image_sizes[0] },
            "Q": { "symbol": "plcc_image_q", "size": c.image_sizes[1] },
            "M": { "symbol": "plcc_image_m", "size": c.image_sizes[2] },
        },
        "at_bindings": c.at_bindings.iter().map(|b| json!({
            "scope": b.scope,
            "name": b.name,
            "address": b.address,
            "area": b.area.to_string(),
            "size_prefix": b.size_prefix.to_string(),
            "byte_offset": b.byte_offset,
            "bit": b.bit,
            "iec_type": b.iec_type,
            "size": b.size,
        })).collect::<Vec<_>>(),
        "tasks": c.tasks.iter().map(|t| json!({
            "name": t.name,
            "interval_ns": t.interval_ns,
            "priority": t.priority,
            "single": t.has_single,
            "instances": t.instances.iter().map(|i| c.instances[*i].name.clone()).collect::<Vec<_>>(),
        })).collect::<Vec<_>>(),
        "instances": c.instances.iter().map(|i| json!({
            "name": i.name,
            "program": i.program,
            "symbol": i.symbol,
            "task": c.tasks.get(i.task).map(|t| t.name.clone()),
        })).collect::<Vec<_>>(),
        "types": c.types.iter().map(struct_json).collect::<Vec<_>>(),
        "globals": c.globals.as_ref().map(struct_json),
        "variables": c.variables.iter().map(|v| json!({
            "path": v.path,
            "symbol": v.symbol,
            "offset": v.offset,
            "size": v.size,
            "iec_type": v.iec_type,
            "retain": v.retain,
            "bit": v.bit,
        })).collect::<Vec<_>>(),
        "fault": {
            "symbol": plcc_runtime::fault::FAULT_SYMBOL,
            "codes": plcc_runtime::fault::FaultCode::ALL.iter().map(|f| json!({
                "name": f.c_name(),
                "code": f.code(),
                "description": f.describe(),
            })).collect::<Vec<_>>(),
            "user_base": plcc_runtime::fault::FAULT_USER_BASE,
        },
        "retain": {
            "signature": c.retain_signature,
            "regions": c.retain.iter().map(|r| json!({
                "path": r.path,
                "symbol": r.symbol,
                "offset": r.offset,
                "size": r.size,
                "iec_type": r.iec_type,
            })).collect::<Vec<_>>(),
        },
    });
    serde_json::to_string_pretty(&v).unwrap_or_default()
}
